/** Canonical BAKUFU mark geometry on a 64-unit grid. Everything that draws the
 * mark (logo-b.tsx, the preloader via logo-b, app/icon.svg and the files in
 * public/brand, generated by scripts/export-brand.ts) reads these paths.
 *
 * Construction:
 * - body: a flat-top kikkō hexagon (R=29, centre 32,32). Its upper-left side is
 *   cut by one open-pit bench: two faces parallel to the hexagon's own 60°
 *   sides with a flat berm between them. One bench, not three: at 16-28px three
 *   benches blur into a rounded, muffin-like top.
 * - seam: the strata cut at y=40, closed at both ends so it never splits the
 *   body, fused with a diamond halo that seats the core. It is a hole in the
 *   body (even-odd), not a drawn line, so the mark stays a single-colour stamp.
 *   It is horizontal on purpose: a dipping or short seam turns the halo into an
 *   almond "eye" at small sizes.
 * - core: the gold reserve, sitting on the strata cut left of centre and
 *   surrounded on every side by the body. It is never in open space.
 */
export const BAKUFU_VIEWBOX = "0 0 64 64";

export const BAKUFU_PATHS = {
  body: "M3 32 10.25 19.5H21L28.25 7H46.5L61 32 46.5 57H17.5Z",
  seam: "M12 37.5H21L30 28.5 39 37.5H52V42.5H39L30 51.5 21 42.5H12Z",
  core: "M30 32.5 37.5 40 30 47.5 22.5 40Z",
  /** Centreline of the strata cut. Drawn only by the hero variant (the scan). */
  scan: "M12 40H52",
} as const;

/** 16px favicon: same body, a heavier cut and a larger core so the separation
 * between core and body stays at least half a device pixel. */
export const BAKUFU_FAVICON_PATHS = {
  body: BAKUFU_PATHS.body,
  seam: "M12 37.25H20.25L30 27.5 39.75 37.25H52V42.75H39.75L30 52.5 20.25 42.75H12Z",
  core: "M30 31.5 38.5 40 30 48.5 21.5 40Z",
} as const;

/** The BAKUFU palette, for the places a CSS variable cannot reach: static SVG
 * exports, canvas and SVG presentation attributes. Mirrors app/globals.css. */
export const BAKUFU_COLORS = {
  ground: "#150C0C",
  shade1: "#1D1616",
  shade2: "#271F1F",
  shade3: "#362C2A",
  paper: "#EACEAA",
  ore: "#85431E",
  glow: "#D39858",
  char: "#34150F",
  ink: "#000000",
} as const;
